[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#1e1e2e"
idle_fg = "#f8f8f2"
info_bg = "#8be9fd"
info_fg = "#282a36"
good_bg = "#50fa7b"
good_fg = "#282a36"
warning_bg = "#f1fa8c"
warning_fg = "#282a36"
critical_bg = "#ff5555"
critical_fg = "#282a36"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome6"

[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"
